### ISSUE TITLE
docker部署成功，但是无法访问

### ISSUE THREAD

**Issue by bkzy333** [zhimin-dev/iptv-checker#71]
阿里云服务器部署，已经确认防火墙已开放了3010，8089，8080端口，
docker-compose.yml文件如下
```
version: "3"
services:
  website:
    image: zmisgod/iptvchecker
    ports:
      - "3010:8080"
    restart: always
```
容器可以正常部署启动，查看容器日志：start web server, port:8089
通过公网IP+3010访问失败，git clone项目到服务器构建镜像也失败了。
![](https://img.zhendafang.top/i/2024/09/01/d8lb90-3.webp)
![](https://img.zhendafang.top/i/2024/09/01/dapun7-3.webp)
![](https://img.zhendafang.top/i/2024/09/01/dg6tt3-3.webp)
